language: ruby
bundler_args: --without tool
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby
  - rbx
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx
notifications:
  recipients:
    - thibaud@thibaud.gg
    - remy@rymai.me
